version: '3.9'

services:
  style-dictionary:
    image: node
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ct-style-dictionary
    restart: always
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
