version: '3.9'

services:
  node:
    image: node
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ct-node
    restart: always
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
